# Medical Superbill Data Extraction Configuration

# Model Configuration
models:
  ocr:
    monkey_ocr:
      model_name: "echo840/MonkeyOCR"
      max_length: 512
      confidence_threshold: 0.7
    nanonets_ocr:
      model_name: "nanonets/Nanonets-OCR-s"
      max_length: 1024
      confidence_threshold: 0.8
  
  extraction:
    nuextract:
      model_name: "numind/NuExtract-2.0-8B"
      max_length: 2048
      temperature: 0.1
      top_p: 0.9

# Document Processing
document_processing:
  pdf:
    dpi: 300
    format: "RGB"
    first_page: null
    last_page: null
  
  image_preprocessing:
    resize_factor: 1.0
    denoise: true
    enhance_contrast: true
    binarize: false
    rotation_correction: true

# Field Extraction Configuration
extraction_fields:
  required_fields:
    - "cpt_codes"
    - "diagnosis_codes"
    - "patient_name"
    - "date_of_service"
    - "claim_date"
    - "provider_info"
  
  optional_fields:
    - "patient_dob"
    - "patient_address"
    - "insurance_info"
    - "procedure_descriptions"
    - "charges"
    - "copay"
    - "deductible"

# Medical Code Patterns
medical_codes:
  cpt_codes:
    pattern: "\\b\\d{5}\\b"
    validation: true
    categories:
      - "evaluation_management"
      - "anesthesia"
      - "surgery"
      - "radiology"
      - "pathology"
      - "medicine"
  
  icd10_codes:
    pattern: "\\b[A-Z]\\d{2}(\\.\\d{1,3})?\\b"
    validation: true
    exclude_patterns:
      - "Z00-Z99"  # Factors influencing health status

# Patient Identification
patient_detection:
  max_patients_per_document: 10
  separation_keywords:
    - "PATIENT"
    - "NAME"
    - "DOB"
    - "ACCOUNT"
    - "CLAIM"
  
  confidence_threshold: 0.8

# Output Configuration
output:
  formats:
    - "json"
    - "csv"
  
  json:
    indent: 2
    ensure_ascii: false
    separators: [",", ": "]
  
  csv:
    delimiter: ","
    quoting: "minimal"
    encoding: "utf-8"

# Security and Compliance
security:
  phi_detection: true
  anonymization: false
  encryption: false
  audit_logging: true
  
  phi_patterns:
    ssn: "\\b\\d{3}-?\\d{2}-?\\d{4}\\b"
    phone: "\\b\\d{3}[-.]?\\d{3}[-.]?\\d{4}\\b"
    email: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"

# Performance Settings
performance:
  batch_size: 4
  max_workers: 4
  gpu_memory_fraction: 0.8
  enable_mixed_precision: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: "logs/extraction.log"
  rotation: "10 MB"
  retention: "30 days"
