# Medical Document Structured Data Extraction Configuration

# Global Configuration
global:
  cache_dir: "models"  # Directory where downloaded models are stored

# Model Configuration
models:
  sequential_loading: true  # Load models sequentially to save VRAM
  unload_after_use: true   # Unload models after processing to free memory

# Processing Configuration
processing:
  use_cuda: true           # Enable CUDA acceleration
  mixed_precision: true    # Use mixed precision for faster inference
  batch_size: 1           # Process in small batches for memory efficiency

# OCR Configuration
ocr:
  # Ensemble configuration (required by code)
  ensemble:
    use_models: ["nanonets_ocr"]
    method: "best_confidence"
    weights:
      nanonets_ocr: 1.0
    minimum_models: 1
    fallback_to_best: true
  
  # Simplified OCR configuration - Nanonets only
  nanonets_ocr:
    model_name: "nanonets/Nanonets-OCR-s"
    local_path: "models/nanonets_Nanonets-OCR-s"
    use_local: true
    max_new_tokens: 2048  # Reduced for faster processing
    timeout: 30  # Reduced timeout
    gpu_optimization: true
    mixed_precision: true

# Extraction Configuration
extraction:
  confidence_threshold: 0.7
  default_template: "medical_superbill"
  confidence_weights:
    ocr: 0.3
    extraction: 0.7
  
  nuextract:
    model_name: "numind/NuExtract-2.0-8B"
    local_path: "models/numind_NuExtract-2.0-8B"
    use_local: true
    max_length: 8192
    temperature: 0.1
    top_p: 0.9
    use_local_cache: true
    cache_dir: "models"
    templates:
      default:
        name: "default"
        description: "Default structured data extraction template"
        schema:
          title: "str"
          date: "str"
          sender: "str"
          receiver: "str"
          content: "str"
          key_points: "list[str]"
          metadata: "dict"
        examples: []
      medical:
        name: "medical"
        description: "Medical document extraction template"
        schema:
          patient_info:
            name: "str"
            dob: "str"
            gender: "str"
            id: "str"
            insurance: "str"
          provider_info:
            name: "str"
            npi: "str"
            address: "str"
          encounter_info:
            date: "str"
            chief_complaint: "str"
            diagnosis: "list[str]"
            procedures: "list[str]"
          billing:
            cpt_codes: "list[str]"
            icd10_codes: "list[str]"
            charges: "dict"
        examples: []

# Document Processing
document_processing:
  pdf:
    dpi: 300
    format: "RGB"
    first_page: null
    last_page: null
    page_batch_size: 3  # Number of pages to process in each batch
  
  image_preprocessing:
    resize_factor: 1.0
    denoise: true
    enhance_contrast: true
    binarize: false
    rotation_correction: true
  
  chunking:
    # Optimized for medical documents and OCR accuracy
    max_width: 800               # Smaller chunks for better OCR accuracy
    max_height: 1000             # Manageable height for medical forms
    overlap_percent: 15          # More overlap to ensure no data is lost at boundaries
    max_tokens_per_chunk: 4000   # Reduced for better processing
    estimated_tokens_per_pixel: 0.0004  # Higher estimate for medical text density
    use_layout_detection: true   # Enable smart chunking based on document structure
    
    # Medical document specific settings
    min_chunk_area_percent: 0.5  # Minimum chunk size as % of page
    form_detection_enabled: true # Look for form structures
    table_aware_chunking: true   # Preserve table structures when chunking

# Patient Detection Configuration
patient_detection:
  max_patients_per_document: 10
  separation_keywords: ["PATIENT", "NAME", "DOB", "ID", "ACCOUNT"]
  enable_patient_differentiation: true
  enhanced_cpt_icd_marking: true

# Export Configuration
export:
  default_format: "json"
  output_dir: "output"
  formats:
    json:
      indent: 2
      ensure_ascii: false
    csv:
      delimiter: ","
      encoding: "utf-8"
    xml:
      indent: "  "
    txt:
      encoding: "utf-8"

# Performance Settings
performance:
  batch_size: 2
  max_workers: 4
  gpu_memory_fraction: 0.8
  enable_mixed_precision: true
  model_loading_timeout: 300  # 5 minutes
  inference_timeout: 60       # 1 minute per inference
  memory_cleanup_interval: 300 # 5 minutes

# Resource Management
resources:
  memory_high_threshold: 85
  memory_critical_threshold: 95
  model_idle_threshold: 600  # 10 minutes before unloading idle models
  cleanup_interval: 120      # 2 minutes between cleanup checks
  max_concurrent_models: 2   # Limit concurrent model loading
  
# Logging Configuration
logging:
  level: "INFO"
  file: "logs/extraction.log"
  rotation: "10 MB"
  retention: "30 days"

# Medical Codes Configuration
medical_codes:
  cpt_patterns: ["\\b\\d{5}\\b", "\\b9\\d{4}\\b"]
  icd_patterns: ["[A-Z]\\d{2}\\.\\d{1,2}", "[A-Z]\\d{2}"]
  validation_enabled: true

# Security Configuration  
security:
  sanitize_output: true
  mask_sensitive_data: true
  audit_logging: true

# Validation Configuration
validation:
  enable_field_validation: true
  confidence_threshold: 0.7
  cross_validation: true
  strict_mode: false

# PHI Anonymization Configuration
phi_anonymization:
  enabled: false
  mask_names: true
  mask_dates: false
  mask_ids: true